# Create your compose file. To learn more, please visit
# https://docs.docker.com/reference/compose-file/
services:
  ollama:
    image: ollama/ollama:latest
    platform: linux/arm64
    ports:
      - "11434:11434"
    volumes:
      - type: bind
        source: /tmp/ollama
        target: /root/.ollama
    command: serve
      
networks:
  default:
    name: hybrid-rag
